// This file is generated by apps/mobile/scripts/generate-alan-stickman-atlases.mjs.
// Do not edit by hand.

export const stickmanSpriteActionIds = [
  "stand",
  "sit",
  "look",
  "dangle",
  "walkFloor",
  "runFloor",
  "runFloorTerminal",
  "falling",
  "recoverFromFloor",
  "nudge",
  "dragged",
  "holdWall",
  "climbWall",
  "holdCeiling",
  "climbCeiling",
  "rest",
  "jump",
  "spawn",
  "tripRecover",
  "pullUp",
  "hugging",
  "hugged",
  "celebrateDance"
] as const;

export type StickmanSpriteActionId = (typeof stickmanSpriteActionIds)[number];

export type StickmanSpriteLoopMode = "hold" | "loop" | "once" | "reserved";

export interface StickmanSpritePoint {
  x: number;
  y: number;
}

export interface StickmanSpriteFrame {
  source: string;
  actionId: StickmanSpriteActionId;
  atlasIndex: number;
  atlasX: number;
  atlasY: number;
  anchor: StickmanSpritePoint;
  velocity: StickmanSpritePoint;
  duration: number;
}

export interface StickmanSpriteSequence {
  id: StickmanSpriteActionId;
  atlas: string;
  frameCount: number;
  frameSize: {
    width: number;
    height: number;
  };
  columns: number;
  rows: number;
  anchor: StickmanSpritePoint;
  durationMs: number;
  velocity: StickmanSpritePoint;
  loop: StickmanSpriteLoopMode;
  reducedMotionFrame: number;
  frames: readonly StickmanSpriteFrame[];
}

export interface StickmanMovementProfile {
  actionId: StickmanSpriteActionId;
  durationMs: number;
  frameIntervalMs: number;
  velocityX: number;
  velocityY: number;
  scaledVelocityX: number;
  scaledVelocityY: number;
  loop: StickmanSpriteLoopMode;
  shouldAnimate: boolean;
  reducedMotionFrame: number;
}

export const alanBlueSpriteSource = {
  sourceDir: "/Users/stephen/work/CFO/alan-stickman-web-demo/img/Blue",
  relativeSourceDir: "../alan-stickman-web-demo/img/Blue",
  packPath: "/Users/stephen/work/CFO/alan-stickman-web-demo/packs/blue/pack.json",
  relativePackPath: "../alan-stickman-web-demo/packs/blue/pack.json",
  totalSourceFrames: 177,
} as const;

export const alanBlueFrameInventory = [
  {
    source: "stand01.png",
    actionId: "stand",
    frameIndex: 0
  },
  {
    source: "sit01.png",
    actionId: "sit",
    frameIndex: 0
  },
  {
    source: "sit_up01.png",
    actionId: "look",
    frameIndex: 0
  },
  {
    source: "sit_legs_up01.png",
    actionId: "dangle",
    frameIndex: 0
  },
  {
    source: "sit_legs_down01.png",
    actionId: "dangle",
    frameIndex: 1
  },
  {
    source: "dangle01.png",
    actionId: "dangle",
    frameIndex: 2
  },
  {
    source: "dangle02.png",
    actionId: "dangle",
    frameIndex: 3
  },
  {
    source: "dangle03.png",
    actionId: "dangle",
    frameIndex: 4
  },
  {
    source: "dangle04.png",
    actionId: "dangle",
    frameIndex: 5
  },
  {
    source: "dangle05.png",
    actionId: "dangle",
    frameIndex: 6
  },
  {
    source: "dangle06.png",
    actionId: "dangle",
    frameIndex: 7
  },
  {
    source: "walk01.png",
    actionId: "walkFloor",
    frameIndex: 0
  },
  {
    source: "walk02.png",
    actionId: "walkFloor",
    frameIndex: 1
  },
  {
    source: "walk03.png",
    actionId: "walkFloor",
    frameIndex: 2
  },
  {
    source: "walk04.png",
    actionId: "walkFloor",
    frameIndex: 3
  },
  {
    source: "walk05.png",
    actionId: "walkFloor",
    frameIndex: 4
  },
  {
    source: "walk06.png",
    actionId: "walkFloor",
    frameIndex: 5
  },
  {
    source: "run01.png",
    actionId: "runFloor",
    frameIndex: 0
  },
  {
    source: "run02.png",
    actionId: "runFloor",
    frameIndex: 1
  },
  {
    source: "run03.png",
    actionId: "runFloor",
    frameIndex: 2
  },
  {
    source: "run04.png",
    actionId: "runFloor",
    frameIndex: 3
  },
  {
    source: "run05.png",
    actionId: "runFloor",
    frameIndex: 4
  },
  {
    source: "run06.png",
    actionId: "runFloor",
    frameIndex: 5
  },
  {
    source: "run07.png",
    actionId: "runFloor",
    frameIndex: 6
  },
  {
    source: "run08.png",
    actionId: "runFloor",
    frameIndex: 7
  },
  {
    source: "run09.png",
    actionId: "runFloor",
    frameIndex: 8
  },
  {
    source: "run10.png",
    actionId: "runFloor",
    frameIndex: 9
  },
  {
    source: "run11.png",
    actionId: "runFloor",
    frameIndex: 10
  },
  {
    source: "run12.png",
    actionId: "runFloorTerminal",
    frameIndex: 0
  },
  {
    source: "fall01.png",
    actionId: "falling",
    frameIndex: 0
  },
  {
    source: "bounce01.png",
    actionId: "recoverFromFloor",
    frameIndex: 0
  },
  {
    source: "bounce02.png",
    actionId: "recoverFromFloor",
    frameIndex: 1
  },
  {
    source: "bounce03.png",
    actionId: "recoverFromFloor",
    frameIndex: 2
  },
  {
    source: "bounce04.png",
    actionId: "recoverFromFloor",
    frameIndex: 3
  },
  {
    source: "pinch01.png",
    actionId: "nudge",
    frameIndex: 0
  },
  {
    source: "pinch02.png",
    actionId: "nudge",
    frameIndex: 1
  },
  {
    source: "pinch03.png",
    actionId: "nudge",
    frameIndex: 2
  },
  {
    source: "pinch04.png",
    actionId: "nudge",
    frameIndex: 3
  },
  {
    source: "pinch05.png",
    actionId: "nudge",
    frameIndex: 4
  },
  {
    source: "pinch06.png",
    actionId: "nudge",
    frameIndex: 5
  },
  {
    source: "pinch07.png",
    actionId: "nudge",
    frameIndex: 6
  },
  {
    source: "hang01.png",
    actionId: "holdWall",
    frameIndex: 0
  },
  {
    source: "wall_climb01.png",
    actionId: "climbWall",
    frameIndex: 0
  },
  {
    source: "wall_climb02.png",
    actionId: "climbWall",
    frameIndex: 1
  },
  {
    source: "wall_climb03.png",
    actionId: "climbWall",
    frameIndex: 2
  },
  {
    source: "wall_climb04.png",
    actionId: "climbWall",
    frameIndex: 3
  },
  {
    source: "wall_climb05.png",
    actionId: "climbWall",
    frameIndex: 4
  },
  {
    source: "swing01.png",
    actionId: "climbCeiling",
    frameIndex: 0
  },
  {
    source: "swing02.png",
    actionId: "climbCeiling",
    frameIndex: 1
  },
  {
    source: "swing03.png",
    actionId: "climbCeiling",
    frameIndex: 2
  },
  {
    source: "swing04.png",
    actionId: "climbCeiling",
    frameIndex: 3
  },
  {
    source: "swing05.png",
    actionId: "climbCeiling",
    frameIndex: 4
  },
  {
    source: "swing06.png",
    actionId: "climbCeiling",
    frameIndex: 5
  },
  {
    source: "swing07.png",
    actionId: "climbCeiling",
    frameIndex: 6
  },
  {
    source: "swing08.png",
    actionId: "climbCeiling",
    frameIndex: 7
  },
  {
    source: "lay01.png",
    actionId: "rest",
    frameIndex: 0
  },
  {
    source: "couch01.png",
    actionId: "rest",
    frameIndex: 1
  },
  {
    source: "jump01.png",
    actionId: "jump",
    frameIndex: 0
  },
  {
    source: "shime1.png",
    actionId: "spawn",
    frameIndex: 0
  },
  {
    source: "trip01.png",
    actionId: "tripRecover",
    frameIndex: 0
  },
  {
    source: "trip02.png",
    actionId: "tripRecover",
    frameIndex: 1
  },
  {
    source: "trip03.png",
    actionId: "tripRecover",
    frameIndex: 2
  },
  {
    source: "trip04.png",
    actionId: "tripRecover",
    frameIndex: 3
  },
  {
    source: "trip05.png",
    actionId: "tripRecover",
    frameIndex: 4
  },
  {
    source: "trip06.png",
    actionId: "tripRecover",
    frameIndex: 5
  },
  {
    source: "pull_up01.png",
    actionId: "tripRecover",
    frameIndex: 6
  },
  {
    source: "pull_up02.png",
    actionId: "tripRecover",
    frameIndex: 7
  },
  {
    source: "pull_up03.png",
    actionId: "tripRecover",
    frameIndex: 8
  },
  {
    source: "pull_up04.png",
    actionId: "tripRecover",
    frameIndex: 9
  },
  {
    source: "pull_up05.png",
    actionId: "tripRecover",
    frameIndex: 10
  },
  {
    source: "pull_up06.png",
    actionId: "tripRecover",
    frameIndex: 11
  },
  {
    source: "pull_up07.png",
    actionId: "tripRecover",
    frameIndex: 12
  },
  {
    source: "hugging_solid01.png",
    actionId: "hugging",
    frameIndex: 0
  },
  {
    source: "hugging_solid02.png",
    actionId: "hugging",
    frameIndex: 1
  },
  {
    source: "hugging_solid03.png",
    actionId: "hugging",
    frameIndex: 2
  },
  {
    source: "hugging_solid04.png",
    actionId: "hugging",
    frameIndex: 3
  },
  {
    source: "hugging_solid05.png",
    actionId: "hugging",
    frameIndex: 4
  },
  {
    source: "hugging_solid06.png",
    actionId: "hugging",
    frameIndex: 5
  },
  {
    source: "hugging_solid07.png",
    actionId: "hugging",
    frameIndex: 6
  },
  {
    source: "hugging_solid08.png",
    actionId: "hugging",
    frameIndex: 7
  },
  {
    source: "hugged_solid01.png",
    actionId: "hugged",
    frameIndex: 0
  },
  {
    source: "hugged_solid02.png",
    actionId: "hugged",
    frameIndex: 1
  },
  {
    source: "hugged_solid03.png",
    actionId: "hugged",
    frameIndex: 2
  },
  {
    source: "hugged_solid04.png",
    actionId: "hugged",
    frameIndex: 3
  },
  {
    source: "hugged_solid05.png",
    actionId: "hugged",
    frameIndex: 4
  },
  {
    source: "hugged_solid06.png",
    actionId: "hugged",
    frameIndex: 5
  },
  {
    source: "hugged_solid07.png",
    actionId: "hugged",
    frameIndex: 6
  },
  {
    source: "hugged_solid08.png",
    actionId: "hugged",
    frameIndex: 7
  },
  {
    source: "dance01.png",
    actionId: "celebrateDance",
    frameIndex: 0
  },
  {
    source: "dance02.png",
    actionId: "celebrateDance",
    frameIndex: 1
  },
  {
    source: "dance03.png",
    actionId: "celebrateDance",
    frameIndex: 2
  },
  {
    source: "dance04.png",
    actionId: "celebrateDance",
    frameIndex: 3
  },
  {
    source: "dance05.png",
    actionId: "celebrateDance",
    frameIndex: 4
  },
  {
    source: "dance06.png",
    actionId: "celebrateDance",
    frameIndex: 5
  },
  {
    source: "dance07.png",
    actionId: "celebrateDance",
    frameIndex: 6
  },
  {
    source: "dance08.png",
    actionId: "celebrateDance",
    frameIndex: 7
  },
  {
    source: "dance09.png",
    actionId: "celebrateDance",
    frameIndex: 8
  },
  {
    source: "dance10.png",
    actionId: "celebrateDance",
    frameIndex: 9
  },
  {
    source: "dance11.png",
    actionId: "celebrateDance",
    frameIndex: 10
  },
  {
    source: "dance12.png",
    actionId: "celebrateDance",
    frameIndex: 11
  },
  {
    source: "dance13.png",
    actionId: "celebrateDance",
    frameIndex: 12
  },
  {
    source: "dance14.png",
    actionId: "celebrateDance",
    frameIndex: 13
  },
  {
    source: "dance15.png",
    actionId: "celebrateDance",
    frameIndex: 14
  },
  {
    source: "dance16.png",
    actionId: "celebrateDance",
    frameIndex: 15
  },
  {
    source: "dance17.png",
    actionId: "celebrateDance",
    frameIndex: 16
  },
  {
    source: "dance18.png",
    actionId: "celebrateDance",
    frameIndex: 17
  },
  {
    source: "dance19.png",
    actionId: "celebrateDance",
    frameIndex: 18
  },
  {
    source: "dance20.png",
    actionId: "celebrateDance",
    frameIndex: 19
  },
  {
    source: "dance21.png",
    actionId: "celebrateDance",
    frameIndex: 20
  },
  {
    source: "dance22.png",
    actionId: "celebrateDance",
    frameIndex: 21
  },
  {
    source: "dance23.png",
    actionId: "celebrateDance",
    frameIndex: 22
  },
  {
    source: "dance24.png",
    actionId: "celebrateDance",
    frameIndex: 23
  },
  {
    source: "dance25.png",
    actionId: "celebrateDance",
    frameIndex: 24
  },
  {
    source: "dance26.png",
    actionId: "celebrateDance",
    frameIndex: 25
  },
  {
    source: "dance27.png",
    actionId: "celebrateDance",
    frameIndex: 26
  },
  {
    source: "dance28.png",
    actionId: "celebrateDance",
    frameIndex: 27
  },
  {
    source: "dance29.png",
    actionId: "celebrateDance",
    frameIndex: 28
  },
  {
    source: "dance30.png",
    actionId: "celebrateDance",
    frameIndex: 29
  },
  {
    source: "dance31.png",
    actionId: "celebrateDance",
    frameIndex: 30
  },
  {
    source: "dance32.png",
    actionId: "celebrateDance",
    frameIndex: 31
  },
  {
    source: "dance33.png",
    actionId: "celebrateDance",
    frameIndex: 32
  },
  {
    source: "dance34.png",
    actionId: "celebrateDance",
    frameIndex: 33
  },
  {
    source: "dance35.png",
    actionId: "celebrateDance",
    frameIndex: 34
  },
  {
    source: "dance36.png",
    actionId: "celebrateDance",
    frameIndex: 35
  },
  {
    source: "dance37.png",
    actionId: "celebrateDance",
    frameIndex: 36
  },
  {
    source: "dance38.png",
    actionId: "celebrateDance",
    frameIndex: 37
  },
  {
    source: "dance39.png",
    actionId: "celebrateDance",
    frameIndex: 38
  },
  {
    source: "dance40.png",
    actionId: "celebrateDance",
    frameIndex: 39
  },
  {
    source: "dance41.png",
    actionId: "celebrateDance",
    frameIndex: 40
  },
  {
    source: "dance42.png",
    actionId: "celebrateDance",
    frameIndex: 41
  },
  {
    source: "dance43.png",
    actionId: "celebrateDance",
    frameIndex: 42
  },
  {
    source: "dance44.png",
    actionId: "celebrateDance",
    frameIndex: 43
  },
  {
    source: "dance45.png",
    actionId: "celebrateDance",
    frameIndex: 44
  },
  {
    source: "dance46.png",
    actionId: "celebrateDance",
    frameIndex: 45
  },
  {
    source: "dance47.png",
    actionId: "celebrateDance",
    frameIndex: 46
  },
  {
    source: "dance48.png",
    actionId: "celebrateDance",
    frameIndex: 47
  },
  {
    source: "dance49.png",
    actionId: "celebrateDance",
    frameIndex: 48
  },
  {
    source: "dance50.png",
    actionId: "celebrateDance",
    frameIndex: 49
  },
  {
    source: "dance51.png",
    actionId: "celebrateDance",
    frameIndex: 50
  },
  {
    source: "dance52.png",
    actionId: "celebrateDance",
    frameIndex: 51
  },
  {
    source: "dance53.png",
    actionId: "celebrateDance",
    frameIndex: 52
  },
  {
    source: "dance54.png",
    actionId: "celebrateDance",
    frameIndex: 53
  },
  {
    source: "dance55.png",
    actionId: "celebrateDance",
    frameIndex: 54
  },
  {
    source: "dance56.png",
    actionId: "celebrateDance",
    frameIndex: 55
  },
  {
    source: "dance57.png",
    actionId: "celebrateDance",
    frameIndex: 56
  },
  {
    source: "dance58.png",
    actionId: "celebrateDance",
    frameIndex: 57
  },
  {
    source: "dance59.png",
    actionId: "celebrateDance",
    frameIndex: 58
  },
  {
    source: "dance60.png",
    actionId: "celebrateDance",
    frameIndex: 59
  },
  {
    source: "dance61.png",
    actionId: "celebrateDance",
    frameIndex: 60
  },
  {
    source: "dance62.png",
    actionId: "celebrateDance",
    frameIndex: 61
  },
  {
    source: "dance63.png",
    actionId: "celebrateDance",
    frameIndex: 62
  },
  {
    source: "dance64.png",
    actionId: "celebrateDance",
    frameIndex: 63
  },
  {
    source: "dance65.png",
    actionId: "celebrateDance",
    frameIndex: 64
  },
  {
    source: "dance66.png",
    actionId: "celebrateDance",
    frameIndex: 65
  },
  {
    source: "dance67.png",
    actionId: "celebrateDance",
    frameIndex: 66
  },
  {
    source: "dance68.png",
    actionId: "celebrateDance",
    frameIndex: 67
  },
  {
    source: "dance69.png",
    actionId: "celebrateDance",
    frameIndex: 68
  },
  {
    source: "dance70.png",
    actionId: "celebrateDance",
    frameIndex: 69
  },
  {
    source: "dance71.png",
    actionId: "celebrateDance",
    frameIndex: 70
  },
  {
    source: "dance72.png",
    actionId: "celebrateDance",
    frameIndex: 71
  },
  {
    source: "dance73.png",
    actionId: "celebrateDance",
    frameIndex: 72
  },
  {
    source: "dance74.png",
    actionId: "celebrateDance",
    frameIndex: 73
  },
  {
    source: "dance75.png",
    actionId: "celebrateDance",
    frameIndex: 74
  },
  {
    source: "dance76.png",
    actionId: "celebrateDance",
    frameIndex: 75
  },
  {
    source: "dance77.png",
    actionId: "celebrateDance",
    frameIndex: 76
  },
  {
    source: "dance78.png",
    actionId: "celebrateDance",
    frameIndex: 77
  },
  {
    source: "dance79.png",
    actionId: "celebrateDance",
    frameIndex: 78
  },
  {
    source: "dance80.png",
    actionId: "celebrateDance",
    frameIndex: 79
  },
  {
    source: "dance81.png",
    actionId: "celebrateDance",
    frameIndex: 80
  },
  {
    source: "dance82.png",
    actionId: "celebrateDance",
    frameIndex: 81
  },
  {
    source: "dance83.png",
    actionId: "celebrateDance",
    frameIndex: 82
  },
  {
    source: "dance84.png",
    actionId: "celebrateDance",
    frameIndex: 83
  },
  {
    source: "dance85.png",
    actionId: "celebrateDance",
    frameIndex: 84
  },
  {
    source: "dance86.png",
    actionId: "celebrateDance",
    frameIndex: 85
  },
  {
    source: "dance87.png",
    actionId: "celebrateDance",
    frameIndex: 86
  },
  {
    source: "dance88.png",
    actionId: "celebrateDance",
    frameIndex: 87
  },
  {
    source: "dance89.png",
    actionId: "celebrateDance",
    frameIndex: 88
  }
] as const;

export const alanBlueSpriteSequences = {
  stand: {
    id: "stand",
    atlas: "stand.png",
    frameCount: 1,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 1,
    rows: 1,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 1000,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "hold",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "stand01.png",
        actionId: "stand",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  sit: {
    id: "sit",
    atlas: "sit.png",
    frameCount: 1,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 1,
    rows: 1,
    anchor: {
      x: 64,
      y: 126
    },
    durationMs: 1000,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "hold",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "sit01.png",
        actionId: "sit",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 126
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  look: {
    id: "look",
    atlas: "look.png",
    frameCount: 1,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 1,
    rows: 1,
    anchor: {
      x: 64,
      y: 126
    },
    durationMs: 1000,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "hold",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "sit_up01.png",
        actionId: "look",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 126
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  dangle: {
    id: "dangle",
    atlas: "dangle.png",
    frameCount: 8,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 8,
    rows: 1,
    anchor: {
      x: 64,
      y: 90
    },
    durationMs: 980,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "loop",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "sit_legs_up01.png",
        actionId: "dangle",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 90
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "sit_legs_down01.png",
        actionId: "dangle",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 90
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dangle01.png",
        actionId: "dangle",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 90
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 8
      },
      {
        source: "dangle02.png",
        actionId: "dangle",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 90
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 2
      },
      {
        source: "dangle03.png",
        actionId: "dangle",
        atlasIndex: 4,
        atlasX: 512,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 90
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "dangle04.png",
        actionId: "dangle",
        atlasIndex: 5,
        atlasX: 640,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 90
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 8
      },
      {
        source: "dangle05.png",
        actionId: "dangle",
        atlasIndex: 6,
        atlasX: 768,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 90
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 2
      },
      {
        source: "dangle06.png",
        actionId: "dangle",
        atlasIndex: 7,
        atlasX: 896,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 90
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      }
    ]
  },
  walkFloor: {
    id: "walkFloor",
    atlas: "walkFloor.png",
    frameCount: 6,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 6,
    rows: 1,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 560,
    velocity: {
      x: -4,
      y: 0
    },
    loop: "loop",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "walk01.png",
        actionId: "walkFloor",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -4,
          y: 0
        },
        duration: 2
      },
      {
        source: "walk02.png",
        actionId: "walkFloor",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -4,
          y: 0
        },
        duration: 2
      },
      {
        source: "walk03.png",
        actionId: "walkFloor",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -4,
          y: 0
        },
        duration: 2
      },
      {
        source: "walk04.png",
        actionId: "walkFloor",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -4,
          y: 0
        },
        duration: 2
      },
      {
        source: "walk05.png",
        actionId: "walkFloor",
        atlasIndex: 4,
        atlasX: 512,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -4,
          y: 0
        },
        duration: 2
      },
      {
        source: "walk06.png",
        actionId: "walkFloor",
        atlasIndex: 5,
        atlasX: 640,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -4,
          y: 0
        },
        duration: 2
      }
    ]
  },
  runFloor: {
    id: "runFloor",
    atlas: "runFloor.png",
    frameCount: 11,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 11,
    rows: 1,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 460,
    velocity: {
      x: -18,
      y: 0
    },
    loop: "loop",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "run01.png",
        actionId: "runFloor",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -18,
          y: 0
        },
        duration: 2
      },
      {
        source: "run02.png",
        actionId: "runFloor",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -18,
          y: 0
        },
        duration: 2
      },
      {
        source: "run03.png",
        actionId: "runFloor",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -18,
          y: 0
        },
        duration: 2
      },
      {
        source: "run04.png",
        actionId: "runFloor",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -18,
          y: 0
        },
        duration: 2
      },
      {
        source: "run05.png",
        actionId: "runFloor",
        atlasIndex: 4,
        atlasX: 512,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -18,
          y: 0
        },
        duration: 2
      },
      {
        source: "run06.png",
        actionId: "runFloor",
        atlasIndex: 5,
        atlasX: 640,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -18,
          y: 0
        },
        duration: 2
      },
      {
        source: "run07.png",
        actionId: "runFloor",
        atlasIndex: 6,
        atlasX: 768,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -18,
          y: 0
        },
        duration: 2
      },
      {
        source: "run08.png",
        actionId: "runFloor",
        atlasIndex: 7,
        atlasX: 896,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -18,
          y: 0
        },
        duration: 2
      },
      {
        source: "run09.png",
        actionId: "runFloor",
        atlasIndex: 8,
        atlasX: 1024,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -18,
          y: 0
        },
        duration: 2
      },
      {
        source: "run10.png",
        actionId: "runFloor",
        atlasIndex: 9,
        atlasX: 1152,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -18,
          y: 0
        },
        duration: 2
      },
      {
        source: "run11.png",
        actionId: "runFloor",
        atlasIndex: 10,
        atlasX: 1280,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -18,
          y: 0
        },
        duration: 2
      }
    ]
  },
  runFloorTerminal: {
    id: "runFloorTerminal",
    atlas: "runFloorTerminal.png",
    frameCount: 1,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 1,
    rows: 1,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 250,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "reserved",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "run12.png",
        actionId: "runFloorTerminal",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  falling: {
    id: "falling",
    atlas: "falling.png",
    frameCount: 1,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 1,
    rows: 1,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 420,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "hold",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "fall01.png",
        actionId: "falling",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  recoverFromFloor: {
    id: "recoverFromFloor",
    atlas: "recoverFromFloor.png",
    frameCount: 4,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 4,
    rows: 1,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 420,
    velocity: {
      x: -1,
      y: 0
    },
    loop: "once",
    reducedMotionFrame: 3,
    frames: [
      {
        source: "bounce01.png",
        actionId: "recoverFromFloor",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: -1,
          y: 0
        },
        duration: 4
      },
      {
        source: "bounce02.png",
        actionId: "recoverFromFloor",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 4
      },
      {
        source: "bounce03.png",
        actionId: "recoverFromFloor",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 4
      },
      {
        source: "bounce04.png",
        actionId: "recoverFromFloor",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 4
      }
    ]
  },
  nudge: {
    id: "nudge",
    atlas: "nudge.png",
    frameCount: 7,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 7,
    rows: 1,
    anchor: {
      x: 64,
      y: 120
    },
    durationMs: 420,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "once",
    reducedMotionFrame: 3,
    frames: [
      {
        source: "pinch01.png",
        actionId: "nudge",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "pinch02.png",
        actionId: "nudge",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "pinch03.png",
        actionId: "nudge",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "pinch04.png",
        actionId: "nudge",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "pinch05.png",
        actionId: "nudge",
        atlasIndex: 4,
        atlasX: 512,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "pinch06.png",
        actionId: "nudge",
        atlasIndex: 5,
        atlasX: 640,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "pinch07.png",
        actionId: "nudge",
        atlasIndex: 6,
        atlasX: 768,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      }
    ]
  },
  dragged: {
    id: "dragged",
    atlas: "dragged.png",
    frameCount: 7,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 7,
    rows: 1,
    anchor: {
      x: 64,
      y: 120
    },
    durationMs: 620,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "loop",
    reducedMotionFrame: 3,
    frames: [
      {
        source: "pinch01.png",
        actionId: "dragged",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "pinch02.png",
        actionId: "dragged",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "pinch03.png",
        actionId: "dragged",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "pinch04.png",
        actionId: "dragged",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "pinch05.png",
        actionId: "dragged",
        atlasIndex: 4,
        atlasX: 512,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "pinch06.png",
        actionId: "dragged",
        atlasIndex: 5,
        atlasX: 640,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      },
      {
        source: "pinch07.png",
        actionId: "dragged",
        atlasIndex: 6,
        atlasX: 768,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 120
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 5
      }
    ]
  },
  holdWall: {
    id: "holdWall",
    atlas: "holdWall.png",
    frameCount: 1,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 1,
    rows: 1,
    anchor: {
      x: 64,
      y: 0
    },
    durationMs: 1000,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "hold",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "hang01.png",
        actionId: "holdWall",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 0
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  climbWall: {
    id: "climbWall",
    atlas: "climbWall.png",
    frameCount: 5,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 5,
    rows: 1,
    anchor: {
      x: 0,
      y: 128
    },
    durationMs: 680,
    velocity: {
      x: 0,
      y: -4
    },
    loop: "loop",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "wall_climb01.png",
        actionId: "climbWall",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 0,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "wall_climb02.png",
        actionId: "climbWall",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 0,
          y: 128
        },
        velocity: {
          x: 0,
          y: -4
        },
        duration: 3
      },
      {
        source: "wall_climb03.png",
        actionId: "climbWall",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 0,
          y: 128
        },
        velocity: {
          x: 0,
          y: -4
        },
        duration: 3
      },
      {
        source: "wall_climb04.png",
        actionId: "climbWall",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 0,
          y: 128
        },
        velocity: {
          x: 0,
          y: -4
        },
        duration: 4
      },
      {
        source: "wall_climb05.png",
        actionId: "climbWall",
        atlasIndex: 4,
        atlasX: 512,
        atlasY: 0,
        anchor: {
          x: 0,
          y: 128
        },
        velocity: {
          x: 0,
          y: -2
        },
        duration: 2
      }
    ]
  },
  holdCeiling: {
    id: "holdCeiling",
    atlas: "holdCeiling.png",
    frameCount: 1,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 1,
    rows: 1,
    anchor: {
      x: 64,
      y: 0
    },
    durationMs: 1000,
    velocity: {
      x: -6,
      y: 0
    },
    loop: "hold",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "swing01.png",
        actionId: "holdCeiling",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 0
        },
        velocity: {
          x: -6,
          y: 0
        },
        duration: 2
      }
    ]
  },
  climbCeiling: {
    id: "climbCeiling",
    atlas: "climbCeiling.png",
    frameCount: 8,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 8,
    rows: 1,
    anchor: {
      x: 64,
      y: 0
    },
    durationMs: 720,
    velocity: {
      x: -6,
      y: 0
    },
    loop: "loop",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "swing01.png",
        actionId: "climbCeiling",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 0
        },
        velocity: {
          x: -6,
          y: 0
        },
        duration: 2
      },
      {
        source: "swing02.png",
        actionId: "climbCeiling",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 0
        },
        velocity: {
          x: -4,
          y: 0
        },
        duration: 2
      },
      {
        source: "swing03.png",
        actionId: "climbCeiling",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 0
        },
        velocity: {
          x: -4,
          y: 0
        },
        duration: 2
      },
      {
        source: "swing04.png",
        actionId: "climbCeiling",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 0
        },
        velocity: {
          x: -4,
          y: 0
        },
        duration: 2
      },
      {
        source: "swing05.png",
        actionId: "climbCeiling",
        atlasIndex: 4,
        atlasX: 512,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 2
        },
        velocity: {
          x: -8,
          y: 0
        },
        duration: 2
      },
      {
        source: "swing06.png",
        actionId: "climbCeiling",
        atlasIndex: 5,
        atlasX: 640,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 4
        },
        velocity: {
          x: -12,
          y: 0
        },
        duration: 2
      },
      {
        source: "swing07.png",
        actionId: "climbCeiling",
        atlasIndex: 6,
        atlasX: 768,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 8
        },
        velocity: {
          x: -10,
          y: 0
        },
        duration: 2
      },
      {
        source: "swing08.png",
        actionId: "climbCeiling",
        atlasIndex: 7,
        atlasX: 896,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 6
        },
        velocity: {
          x: -8,
          y: 0
        },
        duration: 2
      }
    ]
  },
  rest: {
    id: "rest",
    atlas: "rest.png",
    frameCount: 2,
    frameSize: {
      width: 240,
      height: 128
    },
    columns: 2,
    rows: 1,
    anchor: {
      x: 119,
      y: 128
    },
    durationMs: 1400,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "loop",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "lay01.png",
        actionId: "rest",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 119,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "couch01.png",
        actionId: "rest",
        atlasIndex: 1,
        atlasX: 240,
        atlasY: 0,
        anchor: {
          x: 119,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  jump: {
    id: "jump",
    atlas: "jump.png",
    frameCount: 1,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 1,
    rows: 1,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 360,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "hold",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "jump01.png",
        actionId: "jump",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  spawn: {
    id: "spawn",
    atlas: "spawn.png",
    frameCount: 1,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 1,
    rows: 1,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 360,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "hold",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "shime1.png",
        actionId: "spawn",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  tripRecover: {
    id: "tripRecover",
    atlas: "tripRecover.png",
    frameCount: 13,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 13,
    rows: 1,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 1180,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "once",
    reducedMotionFrame: 12,
    frames: [
      {
        source: "trip01.png",
        actionId: "tripRecover",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "trip02.png",
        actionId: "tripRecover",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "trip03.png",
        actionId: "tripRecover",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "trip04.png",
        actionId: "tripRecover",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "trip05.png",
        actionId: "tripRecover",
        atlasIndex: 4,
        atlasX: 512,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "trip06.png",
        actionId: "tripRecover",
        atlasIndex: 5,
        atlasX: 640,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up01.png",
        actionId: "tripRecover",
        atlasIndex: 6,
        atlasX: 768,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up02.png",
        actionId: "tripRecover",
        atlasIndex: 7,
        atlasX: 896,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up03.png",
        actionId: "tripRecover",
        atlasIndex: 8,
        atlasX: 1024,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up04.png",
        actionId: "tripRecover",
        atlasIndex: 9,
        atlasX: 1152,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up05.png",
        actionId: "tripRecover",
        atlasIndex: 10,
        atlasX: 1280,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up06.png",
        actionId: "tripRecover",
        atlasIndex: 11,
        atlasX: 1408,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up07.png",
        actionId: "tripRecover",
        atlasIndex: 12,
        atlasX: 1536,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  pullUp: {
    id: "pullUp",
    atlas: "pullUp.png",
    frameCount: 7,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 7,
    rows: 1,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 720,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "once",
    reducedMotionFrame: 6,
    frames: [
      {
        source: "pull_up01.png",
        actionId: "pullUp",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up02.png",
        actionId: "pullUp",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up03.png",
        actionId: "pullUp",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up04.png",
        actionId: "pullUp",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up05.png",
        actionId: "pullUp",
        atlasIndex: 4,
        atlasX: 512,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up06.png",
        actionId: "pullUp",
        atlasIndex: 5,
        atlasX: 640,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "pull_up07.png",
        actionId: "pullUp",
        atlasIndex: 6,
        atlasX: 768,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  hugging: {
    id: "hugging",
    atlas: "hugging.png",
    frameCount: 8,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 8,
    rows: 1,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 920,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "loop",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "hugging_solid01.png",
        actionId: "hugging",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugging_solid02.png",
        actionId: "hugging",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugging_solid03.png",
        actionId: "hugging",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugging_solid04.png",
        actionId: "hugging",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugging_solid05.png",
        actionId: "hugging",
        atlasIndex: 4,
        atlasX: 512,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugging_solid06.png",
        actionId: "hugging",
        atlasIndex: 5,
        atlasX: 640,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugging_solid07.png",
        actionId: "hugging",
        atlasIndex: 6,
        atlasX: 768,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugging_solid08.png",
        actionId: "hugging",
        atlasIndex: 7,
        atlasX: 896,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  hugged: {
    id: "hugged",
    atlas: "hugged.png",
    frameCount: 8,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 8,
    rows: 1,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 920,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "loop",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "hugged_solid01.png",
        actionId: "hugged",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugged_solid02.png",
        actionId: "hugged",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugged_solid03.png",
        actionId: "hugged",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugged_solid04.png",
        actionId: "hugged",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugged_solid05.png",
        actionId: "hugged",
        atlasIndex: 4,
        atlasX: 512,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugged_solid06.png",
        actionId: "hugged",
        atlasIndex: 5,
        atlasX: 640,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugged_solid07.png",
        actionId: "hugged",
        atlasIndex: 6,
        atlasX: 768,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "hugged_solid08.png",
        actionId: "hugged",
        atlasIndex: 7,
        atlasX: 896,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  },
  celebrateDance: {
    id: "celebrateDance",
    atlas: "celebrateDance.png",
    frameCount: 89,
    frameSize: {
      width: 128,
      height: 128
    },
    columns: 16,
    rows: 6,
    anchor: {
      x: 64,
      y: 128
    },
    durationMs: 2600,
    velocity: {
      x: 0,
      y: 0
    },
    loop: "once",
    reducedMotionFrame: 0,
    frames: [
      {
        source: "dance01.png",
        actionId: "celebrateDance",
        atlasIndex: 0,
        atlasX: 0,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance02.png",
        actionId: "celebrateDance",
        atlasIndex: 1,
        atlasX: 128,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance03.png",
        actionId: "celebrateDance",
        atlasIndex: 2,
        atlasX: 256,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance04.png",
        actionId: "celebrateDance",
        atlasIndex: 3,
        atlasX: 384,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance05.png",
        actionId: "celebrateDance",
        atlasIndex: 4,
        atlasX: 512,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance06.png",
        actionId: "celebrateDance",
        atlasIndex: 5,
        atlasX: 640,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance07.png",
        actionId: "celebrateDance",
        atlasIndex: 6,
        atlasX: 768,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance08.png",
        actionId: "celebrateDance",
        atlasIndex: 7,
        atlasX: 896,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance09.png",
        actionId: "celebrateDance",
        atlasIndex: 8,
        atlasX: 1024,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance10.png",
        actionId: "celebrateDance",
        atlasIndex: 9,
        atlasX: 1152,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance11.png",
        actionId: "celebrateDance",
        atlasIndex: 10,
        atlasX: 1280,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance12.png",
        actionId: "celebrateDance",
        atlasIndex: 11,
        atlasX: 1408,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance13.png",
        actionId: "celebrateDance",
        atlasIndex: 12,
        atlasX: 1536,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance14.png",
        actionId: "celebrateDance",
        atlasIndex: 13,
        atlasX: 1664,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance15.png",
        actionId: "celebrateDance",
        atlasIndex: 14,
        atlasX: 1792,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance16.png",
        actionId: "celebrateDance",
        atlasIndex: 15,
        atlasX: 1920,
        atlasY: 0,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance17.png",
        actionId: "celebrateDance",
        atlasIndex: 16,
        atlasX: 0,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance18.png",
        actionId: "celebrateDance",
        atlasIndex: 17,
        atlasX: 128,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance19.png",
        actionId: "celebrateDance",
        atlasIndex: 18,
        atlasX: 256,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance20.png",
        actionId: "celebrateDance",
        atlasIndex: 19,
        atlasX: 384,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance21.png",
        actionId: "celebrateDance",
        atlasIndex: 20,
        atlasX: 512,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance22.png",
        actionId: "celebrateDance",
        atlasIndex: 21,
        atlasX: 640,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance23.png",
        actionId: "celebrateDance",
        atlasIndex: 22,
        atlasX: 768,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance24.png",
        actionId: "celebrateDance",
        atlasIndex: 23,
        atlasX: 896,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance25.png",
        actionId: "celebrateDance",
        atlasIndex: 24,
        atlasX: 1024,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance26.png",
        actionId: "celebrateDance",
        atlasIndex: 25,
        atlasX: 1152,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance27.png",
        actionId: "celebrateDance",
        atlasIndex: 26,
        atlasX: 1280,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance28.png",
        actionId: "celebrateDance",
        atlasIndex: 27,
        atlasX: 1408,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance29.png",
        actionId: "celebrateDance",
        atlasIndex: 28,
        atlasX: 1536,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance30.png",
        actionId: "celebrateDance",
        atlasIndex: 29,
        atlasX: 1664,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance31.png",
        actionId: "celebrateDance",
        atlasIndex: 30,
        atlasX: 1792,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance32.png",
        actionId: "celebrateDance",
        atlasIndex: 31,
        atlasX: 1920,
        atlasY: 128,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance33.png",
        actionId: "celebrateDance",
        atlasIndex: 32,
        atlasX: 0,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance34.png",
        actionId: "celebrateDance",
        atlasIndex: 33,
        atlasX: 128,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance35.png",
        actionId: "celebrateDance",
        atlasIndex: 34,
        atlasX: 256,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance36.png",
        actionId: "celebrateDance",
        atlasIndex: 35,
        atlasX: 384,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance37.png",
        actionId: "celebrateDance",
        atlasIndex: 36,
        atlasX: 512,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance38.png",
        actionId: "celebrateDance",
        atlasIndex: 37,
        atlasX: 640,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance39.png",
        actionId: "celebrateDance",
        atlasIndex: 38,
        atlasX: 768,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance40.png",
        actionId: "celebrateDance",
        atlasIndex: 39,
        atlasX: 896,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance41.png",
        actionId: "celebrateDance",
        atlasIndex: 40,
        atlasX: 1024,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance42.png",
        actionId: "celebrateDance",
        atlasIndex: 41,
        atlasX: 1152,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance43.png",
        actionId: "celebrateDance",
        atlasIndex: 42,
        atlasX: 1280,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance44.png",
        actionId: "celebrateDance",
        atlasIndex: 43,
        atlasX: 1408,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance45.png",
        actionId: "celebrateDance",
        atlasIndex: 44,
        atlasX: 1536,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance46.png",
        actionId: "celebrateDance",
        atlasIndex: 45,
        atlasX: 1664,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance47.png",
        actionId: "celebrateDance",
        atlasIndex: 46,
        atlasX: 1792,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance48.png",
        actionId: "celebrateDance",
        atlasIndex: 47,
        atlasX: 1920,
        atlasY: 256,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance49.png",
        actionId: "celebrateDance",
        atlasIndex: 48,
        atlasX: 0,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance50.png",
        actionId: "celebrateDance",
        atlasIndex: 49,
        atlasX: 128,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance51.png",
        actionId: "celebrateDance",
        atlasIndex: 50,
        atlasX: 256,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance52.png",
        actionId: "celebrateDance",
        atlasIndex: 51,
        atlasX: 384,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance53.png",
        actionId: "celebrateDance",
        atlasIndex: 52,
        atlasX: 512,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance54.png",
        actionId: "celebrateDance",
        atlasIndex: 53,
        atlasX: 640,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance55.png",
        actionId: "celebrateDance",
        atlasIndex: 54,
        atlasX: 768,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance56.png",
        actionId: "celebrateDance",
        atlasIndex: 55,
        atlasX: 896,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance57.png",
        actionId: "celebrateDance",
        atlasIndex: 56,
        atlasX: 1024,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance58.png",
        actionId: "celebrateDance",
        atlasIndex: 57,
        atlasX: 1152,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance59.png",
        actionId: "celebrateDance",
        atlasIndex: 58,
        atlasX: 1280,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance60.png",
        actionId: "celebrateDance",
        atlasIndex: 59,
        atlasX: 1408,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance61.png",
        actionId: "celebrateDance",
        atlasIndex: 60,
        atlasX: 1536,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance62.png",
        actionId: "celebrateDance",
        atlasIndex: 61,
        atlasX: 1664,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance63.png",
        actionId: "celebrateDance",
        atlasIndex: 62,
        atlasX: 1792,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance64.png",
        actionId: "celebrateDance",
        atlasIndex: 63,
        atlasX: 1920,
        atlasY: 384,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance65.png",
        actionId: "celebrateDance",
        atlasIndex: 64,
        atlasX: 0,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance66.png",
        actionId: "celebrateDance",
        atlasIndex: 65,
        atlasX: 128,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance67.png",
        actionId: "celebrateDance",
        atlasIndex: 66,
        atlasX: 256,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance68.png",
        actionId: "celebrateDance",
        atlasIndex: 67,
        atlasX: 384,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance69.png",
        actionId: "celebrateDance",
        atlasIndex: 68,
        atlasX: 512,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance70.png",
        actionId: "celebrateDance",
        atlasIndex: 69,
        atlasX: 640,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance71.png",
        actionId: "celebrateDance",
        atlasIndex: 70,
        atlasX: 768,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance72.png",
        actionId: "celebrateDance",
        atlasIndex: 71,
        atlasX: 896,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance73.png",
        actionId: "celebrateDance",
        atlasIndex: 72,
        atlasX: 1024,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance74.png",
        actionId: "celebrateDance",
        atlasIndex: 73,
        atlasX: 1152,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance75.png",
        actionId: "celebrateDance",
        atlasIndex: 74,
        atlasX: 1280,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance76.png",
        actionId: "celebrateDance",
        atlasIndex: 75,
        atlasX: 1408,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance77.png",
        actionId: "celebrateDance",
        atlasIndex: 76,
        atlasX: 1536,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance78.png",
        actionId: "celebrateDance",
        atlasIndex: 77,
        atlasX: 1664,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance79.png",
        actionId: "celebrateDance",
        atlasIndex: 78,
        atlasX: 1792,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance80.png",
        actionId: "celebrateDance",
        atlasIndex: 79,
        atlasX: 1920,
        atlasY: 512,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance81.png",
        actionId: "celebrateDance",
        atlasIndex: 80,
        atlasX: 0,
        atlasY: 640,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance82.png",
        actionId: "celebrateDance",
        atlasIndex: 81,
        atlasX: 128,
        atlasY: 640,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance83.png",
        actionId: "celebrateDance",
        atlasIndex: 82,
        atlasX: 256,
        atlasY: 640,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance84.png",
        actionId: "celebrateDance",
        atlasIndex: 83,
        atlasX: 384,
        atlasY: 640,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance85.png",
        actionId: "celebrateDance",
        atlasIndex: 84,
        atlasX: 512,
        atlasY: 640,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance86.png",
        actionId: "celebrateDance",
        atlasIndex: 85,
        atlasX: 640,
        atlasY: 640,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance87.png",
        actionId: "celebrateDance",
        atlasIndex: 86,
        atlasX: 768,
        atlasY: 640,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance88.png",
        actionId: "celebrateDance",
        atlasIndex: 87,
        atlasX: 896,
        atlasY: 640,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      },
      {
        source: "dance89.png",
        actionId: "celebrateDance",
        atlasIndex: 88,
        atlasX: 1024,
        atlasY: 640,
        anchor: {
          x: 64,
          y: 128
        },
        velocity: {
          x: 0,
          y: 0
        },
        duration: 250
      }
    ]
  }
} as const satisfies Record<StickmanSpriteActionId, StickmanSpriteSequence>;
