// This file is generated by apps/mobile/scripts/generate-alan-stickman-atlases.mjs.
// Do not edit by hand.

import type { ImageSourcePropType } from "react-native";
import standAtlas from "../../../../assets/stickman/alan-blue/stand.png";
import sitAtlas from "../../../../assets/stickman/alan-blue/sit.png";
import lookAtlas from "../../../../assets/stickman/alan-blue/look.png";
import dangleAtlas from "../../../../assets/stickman/alan-blue/dangle.png";
import walkFloorAtlas from "../../../../assets/stickman/alan-blue/walkFloor.png";
import runFloorAtlas from "../../../../assets/stickman/alan-blue/runFloor.png";
import runFloorTerminalAtlas from "../../../../assets/stickman/alan-blue/runFloorTerminal.png";
import fallingAtlas from "../../../../assets/stickman/alan-blue/falling.png";
import recoverFromFloorAtlas from "../../../../assets/stickman/alan-blue/recoverFromFloor.png";
import nudgeAtlas from "../../../../assets/stickman/alan-blue/nudge.png";
import draggedAtlas from "../../../../assets/stickman/alan-blue/dragged.png";
import holdWallAtlas from "../../../../assets/stickman/alan-blue/holdWall.png";
import climbWallAtlas from "../../../../assets/stickman/alan-blue/climbWall.png";
import holdCeilingAtlas from "../../../../assets/stickman/alan-blue/holdCeiling.png";
import climbCeilingAtlas from "../../../../assets/stickman/alan-blue/climbCeiling.png";
import restAtlas from "../../../../assets/stickman/alan-blue/rest.png";
import jumpAtlas from "../../../../assets/stickman/alan-blue/jump.png";
import spawnAtlas from "../../../../assets/stickman/alan-blue/spawn.png";
import tripRecoverAtlas from "../../../../assets/stickman/alan-blue/tripRecover.png";
import pullUpAtlas from "../../../../assets/stickman/alan-blue/pullUp.png";
import huggingAtlas from "../../../../assets/stickman/alan-blue/hugging.png";
import huggedAtlas from "../../../../assets/stickman/alan-blue/hugged.png";
import celebrateDanceAtlas from "../../../../assets/stickman/alan-blue/celebrateDance.png";
import type { StickmanSpriteActionId } from "./alan-blue-sprite-manifest.generated";

export const alanBlueAtlasSources = {
  stand: standAtlas,
  sit: sitAtlas,
  look: lookAtlas,
  dangle: dangleAtlas,
  walkFloor: walkFloorAtlas,
  runFloor: runFloorAtlas,
  runFloorTerminal: runFloorTerminalAtlas,
  falling: fallingAtlas,
  recoverFromFloor: recoverFromFloorAtlas,
  nudge: nudgeAtlas,
  dragged: draggedAtlas,
  holdWall: holdWallAtlas,
  climbWall: climbWallAtlas,
  holdCeiling: holdCeilingAtlas,
  climbCeiling: climbCeilingAtlas,
  rest: restAtlas,
  jump: jumpAtlas,
  spawn: spawnAtlas,
  tripRecover: tripRecoverAtlas,
  pullUp: pullUpAtlas,
  hugging: huggingAtlas,
  hugged: huggedAtlas,
  celebrateDance: celebrateDanceAtlas,
} satisfies Record<StickmanSpriteActionId, ImageSourcePropType>;
